import { useState } from "react";
import { parseDateKey } from "../../utils/dateUtils.js";
import TopicsEditor from "./TopicsEditor.jsx";

const TIME = /^([01]\d|2[0-3]):[0-5]\d$/;
function initial(exam, defaultDate) { return exam ? { courseId: exam.courseId, title: exam.title, examDate: exam.examDate, startTime: exam.startTime, endTime: exam.endTime || "", room: exam.room || "", topics: exam.topics || [], notes: exam.notes || "" } : { courseId: "", title: "", examDate: defaultDate || "", startTime: "", endTime: "", room: "", topics: [], notes: "" }; }
function validate(values) { const errors = {}; if (!values.courseId) errors.courseId = "Choose a course."; if (!values.title.trim()) errors.title = "Exam title is required."; if (!parseDateKey(values.examDate)) errors.examDate = "Choose a valid exam date."; if (!TIME.test(values.startTime)) errors.startTime = "Choose a valid start time."; if (values.endTime && !TIME.test(values.endTime)) errors.endTime = "Choose a valid end time."; else if (values.endTime && values.endTime <= values.startTime) errors.endTime = "End time must be later than start time."; if (values.notes.length > 10000) errors.notes = "Notes must be 10,000 characters or fewer."; return errors; }

function ExamForm({ exam, courses, defaultDate, onSubmit, onCancel, submitting, apiError }) {
  const [values, setValues] = useState(() => initial(exam, defaultDate)); const [errors, setErrors] = useState({});
  function update(field, value) { setValues((current) => ({ ...current, [field]: value })); setErrors((current) => ({ ...current, [field]: "" })); }
  function message(field) { return errors[field] ? <p id={`exam-${field}-error`} className="form-error">{errors[field]}</p> : null; }
  async function submit(event) { event.preventDefault(); const next = validate(values); setErrors(next); if (Object.keys(next).length) return; await onSubmit({ ...values, title: values.title.trim(), endTime: values.endTime || null, room: values.room.trim() || null, notes: values.notes.trim() || null }); }
  const input = (field, label, props = {}) => <div className="exam-field"><label htmlFor={`exam-${field}`}>{label}</label><input id={`exam-${field}`} value={values[field]} onChange={(e) => update(field, e.target.value)} aria-invalid={Boolean(errors[field])} aria-describedby={errors[field] ? `exam-${field}-error` : undefined} {...props} />{message(field)}</div>;
  return <form className="exam-form" onSubmit={submit} noValidate><div className="exam-form__grid"><div className="exam-field"><label htmlFor="exam-course">Course *</label><select id="exam-course" value={values.courseId} onChange={(e) => update("courseId", e.target.value)} aria-invalid={Boolean(errors.courseId)} aria-describedby={errors.courseId ? "exam-courseId-error" : undefined} autoFocus><option value="">Select a course</option>{courses.map((course) => <option key={course.id} value={course.id}>{course.code} — {course.name}</option>)}</select>{message("courseId")}</div>{input("title", "Exam Title *", { maxLength: 200, placeholder: "Final Exam" })}{input("examDate", "Exam Date *", { type: "date" })}{input("startTime", "Start Time *", { type: "time" })}{input("endTime", "End Time", { type: "time" })}{input("room", "Room", { maxLength: 80, placeholder: "B12" })}<div className="exam-field exam-field--wide"><TopicsEditor topics={values.topics} onChange={(topics) => update("topics", topics)} error={errors.topics} /></div><div className="exam-field exam-field--wide"><label htmlFor="exam-notes">Notes</label><textarea id="exam-notes" value={values.notes} onChange={(e) => update("notes", e.target.value)} rows="5" maxLength="10000" /><p className="form-hint">Optional · {values.notes.length}/10,000 characters</p>{message("notes")}</div></div>{courses.length === 0 && <p className="assignment-form__notice">Create an active course before adding an exam.</p>}{apiError && <p className="course-form__api-error" role="alert">{apiError}</p>}<div className="course-dialog__actions"><button className="outline-button" type="button" onClick={onCancel} disabled={submitting}>Cancel</button><button className="primary-button" type="submit" disabled={submitting || courses.length === 0}>{submitting ? "Saving…" : exam ? "Save changes" : "Add exam"}</button></div></form>;
}
export default ExamForm;
